import { Aclonica, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const poppins = Poppins({
  weight: ["100", "200", "400", "600", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const aclonica = Aclonica({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-aclonica",
});
export const banglaFont = localFont({
  src: "../../public/fonts/mayaboti-normal.ttf",
});
export const metadata = {
  title: {
    default: "Hero Kidz",
    template: "%s | Hero Kidz",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${aclonica.variable} antialiased`}>
        <main className="md:w-11/12 mx-auto py-2 min-h-[calc(100svh-302px)]">
          {children}
        </main>
      </body>
    </html>
  );
}
