import { Aclonica, Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import localFont from "next/font/local";
import AuthProvider from "@/provider/AuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "600", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const aclonica = Aclonica({
  weight: ["400"],
});
export const banglaFont = localFont({
  src: "../../../public/fonts/mayaboti-normal.ttf",
});
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${aclonica.variable} ${aclonica.variable} antialiased`}
        >
          <header className="md:w-11/12 mx-auto py-2">
            <Navbar></Navbar>
          </header>
          <main className="md:w-11/12 mx-auto py-2 min-h-[calc(100svh-302px)]">
            {children}
          </main>
          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </AuthProvider>
  );
}
